# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		assembler.py
#		Purpose :	Create the assembler LUT
#		Date :		30th June 2023
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import sys

# *******************************************************************************************
#
#							This is an 8 bit rotate left
#
# *******************************************************************************************
def rol(n):
	return (n << 1) + (0 if (n & 0x80) == 0 else 1)

# *******************************************************************************************
#
#								Convert opcode to hash
#
# *******************************************************************************************

def hash(op,trace = False):
	multiplier = 5
	additive = 68
	xor = 165

	values = [ord(c)-ord('A') for c in op.upper()]
	calc = values[0]
	calc = (calc * multiplier + additive ) & 0xFF
	if trace:
		print(";{0:02x}".format(calc))
	calc = (calc + values[1]) & 0xFF
	if trace:
		print(";{0:02x}".format(calc))
	calc = rol(calc)
	if trace:
		print(";{0:02x}".format(calc))
	calc = calc ^ xor
	if trace:
		print(";{0:02x}".format(calc))
	calc = (calc * multiplier + additive ) & 0xFF
	if trace:
		print(";{0:02x}".format(calc))
	calc = (calc + values[2]) & 0xFF
	if trace:
		print(";{0:02x}".format(calc))
	calc = calc & 0xFF
	return calc


# *******************************************************************************************
#
#									Opcodes in order
#
# *******************************************************************************************

opcodes = """
BRK ,ORA izx ,,,TSB zp ,ORA zp ,ASL zp ,RMB zp ,PHP ,ORA imm ,ASL ,,TSB abs ,ORA abs ,ASL abs ,BBR zpr 
BPL rel ,ORA izy ,ORA izp ,,TRB zp ,ORA zpx ,ASL zpx ,RMB zp ,CLC ,ORA aby ,INC ,,TRB abs ,ORA abx ,ASL abx ,BBR zpr 
JSR abs ,AND izx ,,,BIT zp ,AND zp ,ROL zp ,RMB zp ,PLP ,AND imm ,ROL ,,BIT abs ,AND abs ,ROL abs ,BBR zpr 
BMI rel ,AND izy ,AND izp ,,BIT zpx ,AND zpx ,ROL zpx ,RMB zp ,SEC ,AND aby ,DEC ,,BIT abx ,AND abx ,ROL abx ,BBR zpr 
RTI ,EOR izx ,,,,EOR zp ,LSR zp ,RMB zp ,PHA ,EOR imm ,LSR ,,JMP abs ,EOR abs ,LSR abs ,BBR zpr 
BVC rel ,EOR izy ,EOR izp ,,,EOR zpx ,LSR zpx ,RMB zp ,CLI ,EOR aby ,PHY ,,,EOR abx ,LSR abx ,BBR zpr 
RTS ,ADC izx ,,,STZ zp ,ADC zp ,ROR zp ,RMB zp ,PLA ,ADC imm ,ROR ,,JMP ind ,ADC abs ,ROR abs ,BBR zpr 
BVS rel ,ADC izy ,ADC izp ,,STZ zpx ,ADC zpx ,ROR zpx ,RMB zp ,SEI ,ADC aby ,PLY ,,JMP iax ,ADC abx ,ROR abx ,BBR zpr 
BRA rel ,STA izx ,,,STY zp ,STA zp ,STX zp ,SMB zp ,DEY ,BIT imm ,TXA ,,STY abs ,STA abs ,STX abs ,BBS zpr 
BCC rel ,STA izy ,STA izp ,,STY zpx ,STA zpx ,STX zpy ,SMB zp ,TYA ,STA aby ,TXS ,,STZ abs ,STA abx ,STZ abx ,BBS zpr 
LDY imm ,LDA izx ,LDX imm ,,LDY zp ,LDA zp ,LDX zp ,SMB zp ,TAY ,LDA imm ,TAX ,,LDY abs ,LDA abs ,LDX abs ,BBS zpr 
BCS rel ,LDA izy ,LDA izp ,,LDY zpx ,LDA zpx ,LDX zpy ,SMB zp ,CLV ,LDA aby ,TSX ,,LDY abx ,LDA abx ,LDX aby ,BBS zpr 
CPY imm ,CMP izx ,,,CPY zp ,CMP zp ,DEC zp ,SMB zp ,INY ,CMP imm ,DEX ,WAI  ,CPY abs ,CMP abs ,DEC abs ,BBS zpr 
BNE rel ,CMP izy ,CMP izp ,,,CMP zpx ,DEC zpx ,SMB zp ,CLD ,CMP aby ,PHX ,STP  ,,CMP abx ,DEC abx ,BBS zpr 
CPX imm ,SBC izx ,,,CPX zp ,SBC zp ,INC zp ,SMB zp ,INX ,SBC imm ,NOP,,CPX abs ,SBC abs ,INC abs ,BBS zpr 
BEQ rel ,SBC izy ,SBC izp ,,,SBC zpx ,INC zpx ,SMB zp ,SED ,SBC aby ,PLX ,,,SBC abx ,INC abx ,BBS zpr 
"""

opcodes = opcodes.strip().replace("\n",",")
opcodes = [x.strip() for x in opcodes.strip().split(",") ]	
hashValues = []
opName = {}

for i in range(0,256):
	opcode = opcodes[i][:3] 													# opcode.
	hashValue = 0  																# no instruction hash value - this isn't used.
	if opcode != "" and opcode != "BBS" and opcode != "BBR": 					# work out hash code
		hashValue = hash(opcode) 						
		assert hashValue != 0 	
		if hashValue in opName:
			assert opName[hashValue] == opcode,"{0} {1}".format(opcode,opName[hashValue],opcode)
		else:
			opName[hashValue] = opcode
	hashValues.append(hashValue)

assert len(hashValues) == 256

print(";\n;\tThis file is automatically generated.\n;\n")
print("AssemblerLookup:")
print("\t.byte {0}\n".format(",".join([str(x) for x in hashValues])))

hash("BRK",True)