# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		errors.py
#		Purpose :	Error Generators
#		Date :		25th May 2023
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import sys

def caseConvert(s):
	return s[0].upper()+s[1:].lower()
	
errors = open("src/errors/languages/messages."+sys.argv[1]).readlines()
errors = [x for x in errors if x.strip() != "" and not x.startswith("#")]

h1 = open("src/errors/generated/errors.inc","w")
h2 = open("src/errors/generated/errors.asm","w")
h1.write(";\n;\tThis file is automatically generated.\n;\n")
h2.write(";\n;\tThis file is automatically generated.\n;\n")
h2.write("\t.section code\n")
for e in errors:
	e = [x.strip() for x in e.split(":")]
	e[1] = " ".join([caseConvert(x) for x in e[1].split()])
	h1.write("error_{0} .macro\n\tjmp\tErrorV_{0}\n\t.endm\n".format(e[0]))
	h2.write("ErrorV_{0}:\n\tjsr\tErrorHandler\n\t.text\t\"{1}\",0\n".format(e[0],e[1]))
h2.write("\t.send code\n")
h1.close()
h2.close()
	