# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		makelib.py
#		Purpose :	Create the library file.
#		Date :		25th May 2023
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys,math,re

include = []
assembler = []
for root,dirs,files in os.walk("src"):
	for f in files:
		if f.endswith(".asm"):
			assembler.append(root+os.sep+f)
		if f.endswith(".inc"):
			assembler.append(root+os.sep+f)

print(";\n;\tThis file is automatically generated.\n;")
for f in include+assembler:
	for s in open(f).readlines():
		s = s.rstrip()
		print(s)	
	