# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		timestamp.py
#		Purpose :	Create time stamp for code
#		Date :		9th June 2023
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import sys,os
from datetime import *
print(";\n;\tThis file is automatically generated.\n;")
print("\t.text\t\"{0}\"".format(datetime.now().strftime("%y/%m/%d")))