; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		basic.asm
;		Purpose:	BASIC main program
;		Created:	25th May 2023
;		Reviewed: 	25th June 2023
;		Author:		Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.include "build/zramdata.inc"		; zero page usage
		.include "build/osvectors.inc" 		; OS/ROM Vectors

; ************************************************************************************************
;	
;	These can be overridden on the command line. tass64 doesn't support ifdef, god knows why not.
;
; ************************************************************************************************

		.weak
runEdit = 0 								; setting to 1 builds with the program/testing stuff in.
autoRun = 0 								; setting to 1 autoruns program in memory space.
STACK_PAGES = 2 							; number of stack pages.
		.endweak

		* = $800
		.dsection storage

		* = $1000 							; BASIC ROM goes here.
		.dsection code

; ************************************************************************************************
;
;										   Main Program
;
; ************************************************************************************************

		.section code

boot:	
		ldx 	#BASICCODE >> 8 			; common setup, tells BASIC where its memory area is.
		ldy 	#ENDMEMORY >> 8
		jsr 	PGMSetBaseAddress
		jsr 	IFInitialise 				; setup math library

		.if  	runEdit==1 					; run edit check code (checks line editing by "typing in" lots of lines)
		jmp 	TestCode
		.endif

		.if 	autoRun==1 					; run program in memory, mostly used testing autogenerated programs.
		lda 	#12
		jsr 	OSWriteScreen
		jmp 	Command_RUN
		.endif

		jmp 	Command_NEW 				; most just start with this

		.include "include.files" 			; the files 
		.include "build/libmathslib.asmlib" ; the maths library.

		.if runEdit == 1 					; include test data for line edit test.
		* = BASICCODE + $4000 				; stick it well out of the way.
		.include "src/program/testing/testing.asmx"
		.endif

		.send code


; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************

